# These are supported funding model platforms

github: [ancap-screensaver] # Replace with your GitHub username
patreon: ancap-screensaver # Replace with your Patreon username
open_collective: ancap-screensaver # Replace with your Open Collective username
ko_fi: ancap-screensaver # Replace with your Ko-fi username
tidelift: ancap-screensaver # Replace with your Tidelift username
community_bridge: ancap-screensaver # Replace with your Community Bridge username
liberapay: ancap-screensaver # Replace with your Liberapay username
issuehunt: ancap-screensaver # Replace with your IssueHunt username
otechie: ancap-screensaver # Replace with your Otechie username
custom: ["https://ancap-screensaver.com/donate", "https://gumroad.com/ancap-screensaver"]
